import streamlit as st
import pandas as pd
import numpy as np

st.title("My Health Project App")
# -*- coding: utf-8 -*-
"""Project HEALTH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z6PJILvap8MGRDb4cCSSFAu9dW0Zy-ln
"""

import os
# ////////////////////////////////////////////////////////////// ล้างหน้าจอ เริ่ม

def clear_screen():
    os.system("cls")

# ////////////////////////////////////////////////////////////// ล้างหน้าจอ จบ



# ////////////////////////////////////////////////////////////// คำนวณ BMI เริ่ม

def cal_bmi(weight_kg, height_cm):
    height_m = height_cm / 100.0
    if height_m <= 0:
        print("ส่วนสูงต้องมากกว่า 0")
        return None
    else:
        return weight_kg / (height_m * height_m)
        # ////////////////////////////////////////////////////////////// คำนวณ BMI จบ


# ////////////////////////////////////////////////////////////// BMI เริ่ม


def classify_bmi(bmi):
    if bmi >= 30.0:
        return "อ้วนมาก"
    elif 25.0 <= bmi <= 29.9:
        return "อ้วน"
    elif 23.0 <= bmi <= 24.9:
        return "น้ำหนักเกิน"
    elif 18.6 <= bmi <= 22.9:
        return "น้ำหนักปกติ"
    else:
        return "ผอมเกินไป"


def user_prompt(prompt_t):
    while True:
        text = input(prompt_t).strip()
        try:
            value = float(text)
            return value
        except ValueError:
            print("กรอกตัวเลขเท่านั้น")


def bmi_menu():
    print("\nคำนวณหาค่า BMI")
    weight = user_prompt("กรอกน้ำหนัก กิโลกรัม : ")
    height = user_prompt("กรอกส่วนสูง เซนติเมตร : ")
    bmi = cal_bmi(weight, height)
    if bmi is None:
        input("กด Enter เพื่อกลับ...")
        clear_screen()
        return

    category = classify_bmi(bmi)
    print(f"\nผลลัพธ์: BMI = {bmi:.2f}")
    print(f"ระดับ BMI: {category}")
    input("\nกด Enter เพื่อกลับ...")
    clear_screen()


# ////////////////////////////////////////////////////////////// BMI จบ




# ////////////////////////////////////////////////////////////// BMR เริ่ม
def cal_bmr(weight_kg, height_cm, age, gender):

    if gender == "ชาย":
        return 88.362 + 13.397 * weight_kg + 4.799 * height_cm - 5.677 * age
    else:
        return 447.593 + 9.247 * weight_kg + 3.098 * height_cm - 4.330 * age


def bmr_menu():
    print("\nคำนวณหาค่า BMR")
    gender = input("กรอกเพศ ( ชาย : หญิง ): ").strip()
    if gender not in ["ชาย", "หญิง"]:
        print("ไม่พบเพศที่เลือก กรุณาลองใหม่")
        clear_screen()
        return

    age = user_prompt("กรอกอายุ (ปี): ")
    weight = user_prompt("กรอกน้ำหนัก กิโลกรัม : ")
    height = user_prompt("กรอกส่วนสูง เซนติเมตร : ")

    bmr = cal_bmr(weight, height, age, gender)
    print(f"\nผลลัพธ์: BMR = {bmr:.2f} แคลอรี่/วัน")
    print("\nคำแนะนำสำหรับคุณ")
    print("- หากต้องการ 'ลดน้ำหนัก': ทานแคลอรี่ให้ น้อยกว่า ค่า BMR")
    print("- หากต้องการ 'คุมน้ำหนัก': ทานแคลอรี่เท่ากับ ค่า BMR")
    print("- หากต้องการ 'เพิ่มน้ำหนัก': ทานแคลอรี่มากกว่า ค่า BMR")
    input("\nกด Enter เพื่อกลับ...")
    clear_screen()


# ////////////////////////////////////////////////////////////// BMR จบ


# ////////////////////////////////////////////////////////////// TDEE เริ่ม

def cal_tdee(bmr, activity_level):
    """คำนวณ TDEE ตามระดับการออกกำลังกาย

    ออกกำลังกายน้อยมาก หรือไม่ออกเลย: TDEE = 1.2 x BMR
    ออกกำลังกาย 1-3 ครั้งต่อสัปดาห์: TDEE = 1.375 x BMR
    ออกกำลังกาย 4-5 ครั้งต่อสัปดาห์: TDEE = 1.55 x BMR
    ออกกำลังกาย 6-7 ครั้งต่อสัปดาห์: TDEE = 1.725 x BMR
    ออกกำลังกายวันละ 2 ครั้งขึ้นไป: TDEE = 1.9 x BMR
    """
    multipliers = {
        "1": 1.2,    # น้อยมาก หรือไม่ออกเลย
        "2": 1.375,  # 1-3 ครั้งต่อสัปดาห์
        "3": 1.55,   # 4-5 ครั้งต่อสัปดาห์
        "4": 1.725,  # 6-7 ครั้งต่อสัปดาห์
        "5": 1.9     # วันละ 2 ครั้งขึ้นไป
    }
    return bmr * multipliers.get(activity_level, 1.2)

def get_activity_level():
    """รับระดับการออกกำลังกายจากผู้ใช้"""
    print("\nเลือกระดับการออกกำลังกาย:")
    print("1) ออกกำลังกายน้อยมาก หรือไม่ออกเลย")
    print("2) ออกกำลังกาย 1-3 ครั้งต่อสัปดาห์")
    print("3) ออกกำลังกาย 4-5 ครั้งต่อสัปดาห์")
    print("4) ออกกำลังกาย 6-7 ครั้งต่อสัปดาห์")
    print("5) ออกกำลังกายวันละ 2 ครั้งขึ้นไป")

    while True:
        choice = input("เลือก (1-5): ").strip()
        if choice in ["1", "2", "3", "4", "5"]:
            return choice
        else:
            print("กรุณาเลือก 1-5 เท่านั้น")

def tdee_menu():
    print("\nคำนวณหาค่า TDEE")
    print("(ต้องคำนวณ BMR ก่อน)")


    gender = input("กรอกเพศ ( ชาย : หญิง ): ").strip()
    if gender not in ["ชาย", "หญิง"]:
        print("ไม่พบเพศที่เลือก กรุณาลองใหม่")
        clear_screen()
        return

    age = user_prompt("กรอกอายุ (ปี): ")
    weight = user_prompt("กรอกน้ำหนัก กิโลกรัม : ")
    height = user_prompt("กรอกส่วนสูง เซนติเมตร : ")


    bmr = cal_bmr(weight, height, age, gender)
    print(f"\nBMR = {bmr:.2f} แคลอรี่/วัน")


    activity_level = get_activity_level()


    tdee = cal_tdee(bmr, activity_level)

    print(f"\nผลลัพธ์: TDEE = {tdee:.2f} แคลอรี่/วัน")
    print("\nคำแนะนำสำหรับคุณ:")
    print(f"- หากต้องการ 'ลดน้ำหนัก': ทานแคลอรี่ให้น้อยกว่า {tdee:.0f} แคลอรี่/วัน")
    print(f"- หากต้องการ 'คุมน้ำหนัก': ทานแคลอรี่เท่ากับ {tdee:.0f} แคลอรี่/วัน")
    print(f"- หากต้องการ 'เพิ่มน้ำหนัก': ทานแคลอรี่มากกว่า {tdee:.0f} แคลอรี่/วัน")
    input("\nกด Enter เพื่อกลับ...")
    clear_screen()


# ////////////////////////////////////////////////////////////// TDEE จบ


# ////////////////////////////////////////////////////////////// เมนูหลัก เริ่ม


def print_menu():
    print("\n==============================")
    print("     โปรแกรมคำนวณสุขภาพ")
    print("==============================")
    print("1.) คำนวณ BMI ดัชนีมวลกาย")
    print("2.) คำนวณ BMR อัตราการเผาผลาญพื้นฐาน")
    print("3.) คำนวณ TDEE พลังงานที่ต้องใช้ต่อวัน")
    print("q.) ออกจากโปรแกรม")


def main():
    while True:
        print_menu()
        choice = input("เลือกเมนู: ").strip().lower()

        if choice == "1":
            bmi_menu()
        elif choice == "2":
            bmr_menu()
        elif choice == "3":
            tdee_menu()
        elif choice in {"q"}:
            print("\nขอบคุณที่ใช้งานนนนนนนนน")
            break
        else:
            print("\nไม่พบเมนูที่เลือก กรุณาลองใหม่")
            input("กด Enter เพื่อเคลียร์หน้าจอ...")
            clear_screen()


# ////////////////////////////////////////////////////////////// เมนูหลัก จบ


main()
